import { supabase } from "@/lib/supabase";
import { ComparisonCard } from "@/components/comparison-card";
import type { GeneratedPage } from "@/lib/types";
import { Zap, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const revalidate = 86400; // 24 hours

export const metadata = {
  title: "All SaaS Comparisons | SoftRYT",
  description: "Browse our complete directory of in-depth, AI-generated analysis and comparisons of the most popular B2B SaaS tools.",
};

export default async function ComparisonsPage() {
  const { data: pages } = await supabase
    .from("generated_pages")
    .select("*, tool_a:tools!tool_a_id(logo_url), tool_b:tools!tool_b_id(logo_url)")
    .eq("published_status", "published")
    .order("updated_at", { ascending: false });

  const typedPages = (pages || []) as GeneratedPage[];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-20 min-h-screen">
      <div className="mb-10">
        <Link href="/">
          <Button variant="ghost" size="sm" className="mb-6 -ml-3 text-muted-foreground hover:text-primary">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </Link>
        <h1 className="text-4xl font-bold tracking-tight mb-4">
          All Comparisons
        </h1>
        <p className="text-muted-foreground text-lg max-w-2xl">
          Browse our complete directory of in-depth, AI-generated analysis and comparisons of the most popular B2B SaaS tools.
        </p>
      </div>

      {typedPages.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {typedPages.map((page) => (
            <ComparisonCard key={page.id} page={page} />
          ))}
        </div>
      ) : (
        <div className="text-center py-24 border border-dashed border-border/50 rounded-2xl bg-muted/10">
          <Zap className="h-10 w-10 text-muted-foreground/40 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-muted-foreground mb-2">
            No comparisons yet
          </h3>
          <p className="text-sm text-muted-foreground/60">
            Comparisons will appear here once generated by the AI pipeline.
          </p>
        </div>
      )}
    </div>
  );
}
